### ISSUE TITLE
Documentation on loading different versions of a CryptoKeyVersion

### ISSUE THREAD

**Issue by DolceTriade** [GoogleCloudPlatform/kms-integrations#12]
Hello,

We are trying to perform operations using different versions of the keys to support older clients.

What is the syntax to use the older versions of the keys?

`openssl req -new -x509 -days 3650 -subj '/CN=test/' -sha256 -engine pkcs11   -keyform engine -key pkcs11:object=keyName > my-request.crt`

Seems to always use the latest one?

**Comment by tdbhacks** [comment]
Hello,

Correct, using `pkcs11:object` along with the CryptoKey name defaults to the latest version. The IDs set by our library, which can be used with `pkcs11:id`, correspond to the full KMS resource name (eg. `projects/some_project/locations/some_location/keyRings/some_keyring/cryptoKeys/some_CK/cryptoKeyVersions/1`).

You should be able to use
```
openssl req -new -x509 -days 3650 -subj '/CN=test/' -sha256 -engine pkcs11   -keyform engine -key pkcs11:id=projects/...../cryptoKeyVersions/X;type=private > my-request.crt
```
where X is the right version number.

Note that, when invoking `pkcs11-tool` with `-O` to list the objects, the key IDs are automatically hex-encoded by the tool and may seem different at first.

**Comment by DolceTriade** [comment]
Ahh, thanks so much! I couldn't find any documentation on the ID field in the website!

**Comment by OhZedTee** [comment]
Can we please update the user-guide and KMS documentation to include reference to this? There are no currently available docs highlighting the ability to call on the cryptoKeyVersion by id.

**Comment by bdhess** [comment]
Yeah that's a very reasonable ask - will do.

**Comment by OhZedTee** [comment]
Thank you @bdhess, much appreciated.

**Comment by tdbhacks** [comment]
This is now part of both the [user guide](https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/docs/user_guide.md#other-notes) and the cloud.google.com reference docs.
