### ISSUE TITLE
Only HMS keys, not software ones?

### ISSUE THREAD

**Issue by jonsmirl** [GoogleCloudPlatform/kms-integrations#13]
Is that what this means? "unsupported protection level 1"
~~~
joe@instance-2:~$ openssl req -new -subj '/CN=test/' -sha256 -engine pkcs11 \
  -keyform engine -key pkcs11:object=foo > my-request.csr
engine "pkcs11" set.
I20230414 16:10:07.377626  1704 object_loader.cc:39] key projects/lowpan-32323/locations/us-central1/keyRings/test/cryptoKeys/foo is not loadable due to unsupported protection level 1
No private keys found.
Key not found.
~~~

**Comment by tdbhacks** [comment]
That's correct, our library only supports HSM keys, but we probably want to make that error more readable so thanks for flagging this.

Note that the error above is non-blocking, so it will still show up if your keyring has a mixture of `SOFTWARE` and `HSM` keys, but the library will function correctly when using the HSM key.

**Comment by jonsmirl** [comment]
Is there an alternative openssl plug-in which will use the software keys?

**Comment by jonsmirl** [comment]
The use-case is Matter support for home automation devices. Each house needs its own self-signed RootCA. So that means I need a 100K+ RootCAs. This is not sensitive enough to need hardware key storage. The RootCA is rarely used. When you first install the Matter app on your phone it will use the cloud RootCA to make an IntermediateCA. That IntermediateCA lives on the phone and can make more certificates as needed. If you switch phones or add a second user in the house, then you need to use the RootCA to make another IntermediateCA. My plan was to use software KMS keys for this and then use openssl to process the occasional CSRs. Maybe that's the wrong strategy and I should just keep the keys in a database.

**Comment by tdbhacks** [comment]
Absolutely, makes sense that you don't really need HSM-backed keys for your use case.

Unfortunately the tl;dr here is that we just don't offer support for SOFTWARE keys at all, regardless of whether that flow is performed through openssl or directly, and we are not planning to add for it at this time. I've added a short note to our [FAQs](https://github.com/GoogleCloudPlatform/kms-integrations/wiki/PKCS%2311-FAQs) in the wiki to mention this, sorry about that.

**Comment by tdbhacks** [comment]
@jonsmirl I was going through the closed issues and noticed this one. FYI, software support has been added to v1.5 of the library, and software key creation support is part of the latest v1.6 release. Hope this helps, though I know it's been a while since this issue was first filed!
