### ISSUE TITLE
How to get the Pin and Password to access GCP 

### ISSUE THREAD

**Issue by vishnubraj** [GoogleCloudPlatform/kms-integrations#14]
I am trying to GCP HSM for Hashicorp Vault unseal purposes, The vault config requires the PIN, username: and password to access the HSM, how do I get this?  currently, I am having the service account JSON key. 

https://developer.hashicorp.com/vault/docs/configuration/seal/pkcs11#pin

**Comment by tdbhacks** [comment]
Our PKCS#11 library implements `C_Login` for compatibility purposes, but login is not required. Per the [functions section](https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/docs/user_guide.md#functions) of the user guide:

> Login is not required, and is implemented only to provide compatibility with clients that expect to log in. Login is only permitted for the user role (CKU_USER). Any supplied PIN is ignored.

To authenticate to GCP through our library, you only need your service account credentials. See the [authentication section](https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/docs/user_guide.md#authentication-and-authorization) of the user guide.

**Comment by bdhess** [comment]
I would also note, Vault's [GCPKMS seal](https://developer.hashicorp.com/vault/docs/configuration/seal/gcpckms) would accomplish the same thing and ought to be easier to configure.
