### ISSUE TITLE
CKM_AES_KEY_GEN is not valid for operation GenerateKey

### ISSUE THREAD

**Issue by kenneth-yue** [GoogleCloudPlatform/kms-integrations#27]
According to the documentation at https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/docs/user_guide.md#generic-secret-key-generation, CKM_AES_KEY_GEN is a compatible mechanism for C_GenerateKey. However, when I tried to specify CKM_AES_KEY_GEN as the mechanism when calling C_GenerateKey, I got the following error:

mechanism 0x1080 is not valid for operation GenerateKey [type.googleapis.com/kmsp11.StatusDetails='CK_RV=0x70']

I then looked at your source code and found that https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/session.cc#L498 is allowing only CKM_GENERIC_SECRET_KEY_GEN but not CKM_AES_KEY_GEN.  Why does the code conflict with the documentation? Is this intentional?

**Comment by tdbhacks** [comment]
You are correct, our documentation has been updated incorrectly and should not report `CKM_AES_KEY_GEN` in the list of available mechanisms. We have not added support for AES key generation yet, and it's part of our list of feature requests. I will update our documentation accordingly.

If you are interested in this feature, would you mind explaining your use case in a couple sentences, so that we can evaluate and take your request into account?

Thank you for using Cloud KMS!

**Comment by kenneth-yue** [comment]
AES key generation is actually working.  The mechanism itself is defined in your code (see https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/mechanism.cc#L196) and there are algorithms in your code that handle it (see https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/algorithm_details.cc#L251). There are even tests for it! For example, https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/algorithm_details_test.cc#L78.

I did download your code, added this CKM_AES_KEY_GEN mechanism to this line (https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/session.cc#L501), then rebuilt the code.  Guess what? It worked.  By using the patched library, an AES256 encryption is generated in the Cloud HSM and I could use it to encrypt and decrypt.

My use case is very simple.: use an AES256 symmetric key in Google Cloud HSM for CBC encryption and decryption.  Also a separate key for signing, but that's already supported by your code (https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/session.cc#L499).

**Comment by tdbhacks** [comment]
Correct, most of the implementation should already be in place and I'm happy to hear that you have been able to test it successfully. That's great! But I wouldn't declare it fully supported yet: for example, it only allows AES256 keys right now (`ulMinKeySize`), but we also support AES128 variants

https://github.com/GoogleCloudPlatform/kms-integrations/blob/3945e95cdc4240163868c17648ac5d48c39a8581/kmsp11/mechanism.cc#L196-L201

I think we also don't have good test coverage, the test you pointed to is just to check that the algorithm definition is correct, but we don't go through the actual flow of creating a key. Point well taken though, I have added this code a while back and thought we needed a bit more work here, but it looks like this is pretty close to being ready.

Thanks again for taking the time to test!

**Comment by tdbhacks** [comment]
This is fixed at head and a little more robust now, thanks @kenneth-yue for reporting this! I'll keep this issue open until we eventually publish another release which includes this change.
