### ISSUE TITLE
pdf signing

### ISSUE THREAD

**Issue by mbrevda** [GoogleCloudPlatform/kms-integrations#39]
Is there an example of PDF signing with KMS? [node-pdfsiger](https://github.com/vbuch/node-signpdf/issues/270#issuecomment-2341580954) pointed here, but not sure how to proceed. Thanks!

**Comment by tdbhacks** [comment]
Apologies for the late reply! Unfortunately we don't have an example for PDF signing, our PKCS#11 library should work with other PKCS#11-based PDF signing libraries (eg. this is a sample result that came up: https://kbdeveloper.qoppa.com/apply-digital-signature-on-a-pdf-document-using-hardware-token-pkcs-11/), but I'm not very familiar with what's available for this use case and what the requirements are for PDF signing specifically.

Closing this issue for now, but if you'd like to eventually come back to this and share what worked for you, that would be great!
