### ISSUE TITLE
Version 1.1 now required?

### ISSUE THREAD

**Issue by chris-allan** [GoogleCloudPlatform/kms-integrations#4]
We've been using version 1.0 of this package with GitHub Actions (on Ubuntu 20.04) quite happily for several months to sign artifacts using a signing key in a Google KMS HSM. Recently, our builds started failing with errors like this:

```
...
kmsp11 failure occurred prior to library initialization: returning 0x30 from C_Initialize due to status UNAVAILABLE: 502:Bad Gateway [type.googleapis.com/kmsp11.StatusDetails='CK_RV=0x30']
...
```

Upgrading to 1.1 fixed the problem.

I didn't notice anything in particular in the release notes that jumped out as the reason beyond "Several internal dependencies were updated." Is it safe to say that 1.1 is now a requirement across the board and we should update all our code signing repositories accordingly or is there something else potentially afoot that would be useful for us to help debug?

**Comment by chris-allan** [comment]
Thanks, @bdhess. Let us know if there's anything we can do to help.

**Comment by bdhess** [comment]
Compatibility has been restored, globally.  Thanks again for raising this issue.
